### PR TITLE
Attempt to try and solve issue #111

### PR DESCRIPTION
**Pull request by Quacky2200**
->New algorithm to check country/track availability using LINQ - it's now easier to understand
->3 new EventEmitters in track.js (region-error, network-error, play-success).
->region error occurs when the track and track alternatives cannot be played and can be dealt with easier
->New-ish bug found that I've named network/protocol error. What happens is that every now and then, when our client sends off a trackURI request, Spotify will reply back with an error, this is not a region error (I can play this track on the Spotify app), I've since named it in the EventEmitters as 'network-error' so that my temporary solution can work. The work-around solution I've found to date, includes a re-login and starting from where you were, from then on, Spotify will continue to work. This may be to do with the heartbeat or the set of messages sent from spotify due to timing however, resending messages with the current socket has not worked for me.
->mixtape.js is a small script based on play.js that plays a list of tracks for 8 seconds each.
->play.js updated to work on issue #111. I've found that the old Spotify URI given, gave me 'Failed to send to backend' errors so I've temporarily changed it.

I apologize for some of the changes without comments.

Missing comments:
File spotify.js Line 400-404 - I had changed this as this only occurred on a network error
File spotify.js Line 1330+ - An easier method of checking if an item is within an array, the double ampersands prevent the second if statement to be validated if the first one isn't true.

### CODE REVIEW

**Comment by DoMation666** [comment]
ops i'am really sorry , this tool (Spotifyangel) has too many repositories (socket.io , async , ws , request , express , spotify-web) could you try to fix it ? and if it possible if i can add you on facebook you are very tough in JS :smile: 
ah BTW this is SILENTANGEL blogspot you may get interested in this tool , it's so much easy and flexible :  Spotify MP3 Downloader [SilentAngel] : http://tehexplo.blogspot.com.eg/2015/09/spotify-mp3-downloader-silentangel.html
download link in resources : https://openload.co/f/JzBoUqrbGD4/

**Comment by Quacky2200** [comment]
The node modules are required from what I've heard from SilentAngel's Spotify Downloader as it hosts a website for user accessibility. 

Here's a clue to what they do:
socket.io and ws are both socket handling modules (most likely for communication between the client and web server)
async - some kind of module for asyncronous functions
express - used as a framework for web hosting
request used in tandem with express

**Comment by filfat** [comment]
Quite a hefty commit there :)

 a few things:
1. The linq require statement seem to throw "no path provided" occasionally.
2. Always receives a network error using both Premium and Free account.

 Anyhow <3 the work and hope we can get this sorted out real soon :)

**Comment by Quacky2200** [comment]
Yeah it was quite the debug but I tried to do as much with how much I knew currently know with Node. I had never found the LINQ no path provided error so thanks for finding that :) 

The network error requires a re-login when I get them so I'm really not exactly sure how to really solve it, I thought it was something with the authentication/heartbeat but can't find it anywhere where it could go wrong... :S

**Comment by filfat** [comment]
@Quacky2200 I solved the linq error by just requiring it together with everything else instead of inside a function scope

**Comment by Quacky2200** [comment]
Ahh, well since I didn't want to affect the main code, I just left it in there thinking it would be fine o.0 especially considering how there was only 1 LINQ statement used out of the whole project

**Comment by filfat** [comment]
Seem to be getting the following by running "play.js" using both Premium and Free accounts

> Please wait...
> This is taking longer than usual. Please wait.
> A network/protocol error prevented me getting the audio track. Trying for the last time.
> Giving up...

**Comment by Quacky2200** [comment]
You can increase how many times it retries before it gives up, however if it doesn't work after around 20-30 goes then something is definitely wrong, I wonder what the error is considering it's not a country error. Why would Spotify send an error like that unless the client was doing something wrong?

**Comment by filfat** [comment]
Yep, something is wrong; I keep on getting network error (though enabling debug doesn't show anything out of the ordinary)... 🤔

**Comment by Quacky2200** [comment]
The only time when it gives a network error is when it asks for a track URI and when that happens you can't ask for any track URI so it must be something with the authentication/heartbeat messages. I haven't seen heartbeat ping-pongs in the Web Player so maybe this has been removed? The only message I see is user_active if you look at this: https://github.com/Quacky2200/Spotify-Web-Player-for-Linux/blob/master/scripts/spotify-player.js#L86 (I have interpreted that spb-connected is when login is successful for the web player since it only starts the socket when authentication is complete). However, I could be wrong about the authentication side, last time I checked the authentication on this, it was done by web requests?)

Have you tried a different track URI? Just in case albeit I still doubt it.

Edit: I cannot seem to recreate your errors so far, I have gotten network errors every now and then but they normally get resolved on the next login. I have changed the heartbeatInterval to the difference I found in my web browser (which was 60023-ish instead of 180000) it seemed to work better and I tested it around 50 times, however, it could just be a co-incidence as the bug seems to float around

**Comment by LinusU** [comment]
Maybe I'm missing something, but how is linq helping you keep the code more readable? Isn't this:

``` javascript
Enumerable.from(track.restriction).where(function(x){return membership in x.catalogue}).first()
```

Equal to:

``` javascript
track.restriction.filter(function(x){return membership in x.catalogue})[0]
```

And also equal to:

``` javascript
track.restriction.filter((x) => membership in x.catalogue)[0]
```

And the nicest one, which also doesn't traverse the whole array:

``` javascript
track.restriction.find((x) => membership in x.catalogue)
```

Which to me is more readable, shorter and doesn't require a third party library. Am I missing something?

**Comment by filfat** [comment]
@Quacky2200 Here's the log http://pastebin.com/VRbb16eS

**Comment by Quacky2200** [comment]
You're very right, there is a filter, I had never used/found that, thanks for telling me (facepalm)
Here is what I've changed, not like it makes much of a difference for you atm I bet!
updated function

http://pastebin.com/umg3vrSH

With a lamda:
updated function with lamda

http://pastebin.com/g5Ewg0CQ

By the way, you have a lot of 'undefined' in your debug, I really can't tell why, it's very odd. When you ran 'npm install' did you get any errors? What OS are you using?

**Comment by filfat** [comment]
@Quacky2200  That's because I enabled debugging the improper way the "undefined" is supposed to be the string "spotify-web".

No, NPM works fine both locally and in production.  Windows 10 & Windows Server 2012.

**Comment by Quacky2200** [comment]
Can you run the original code OK without my pull?

Also, I've found with Ubuntu that I had to have quite a lot of dependancies to get the npm install to work as it had to use a lot of development libraries

Other than that, I don't know if I can really help as my code works perfectly on Ubuntu and I'm not that determined to get this working as it was just a fix, and I've finished my interest in this repo since I had found another way of coding what I had originally wanted

**Comment by filfat** [comment]
Everything used to work till a few days ago.

Though the module seem to detect track not being available in the account's country just fine it just always seem to fail when actually getting the track

**Pull request closed without merging**
